/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as LoadsRouteImport } from './routes/loads'
import { Route as MyBidsRouteImport } from './routes/my-bids'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TripDetailsRouteImport } from './routes/trip-details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadsRoute = LoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBidsRoute = MyBidsRouteImport.update({
  id: '/my-bids',
  path: '/my-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TripDetailsRoute = TripDetailsRouteImport.update({
  id: '/trip-details',
  path: '/trip-details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/driver': typeof DriverRoute
  '/loads': typeof LoadsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-requests': typeof MyRequestsRoute
  '/my-trips': typeof MyTripsRoute
  '/offers': typeof OffersRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/trip-details': typeof TripDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/driver': typeof DriverRoute
  '/loads': typeof LoadsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-requests': typeof MyRequestsRoute
  '/my-trips': typeof MyTripsRoute
  '/offers': typeof OffersRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/trip-details': typeof TripDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/driver': typeof DriverRoute
  '/loads': typeof LoadsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-requests': typeof MyRequestsRoute
  '/my-trips': typeof MyTripsRoute
  '/offers': typeof OffersRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/trip-details': typeof TripDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/driver'
    | '/loads'
    | '/my-bids'
    | '/my-requests'
    | '/my-trips'
    | '/offers'
    | '/request'
    | '/settings'
    | '/tracking'
    | '/trip-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/driver'
    | '/loads'
    | '/my-bids'
    | '/my-requests'
    | '/my-trips'
    | '/offers'
    | '/request'
    | '/settings'
    | '/tracking'
    | '/trip-details'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/driver'
    | '/loads'
    | '/my-bids'
    | '/my-requests'
    | '/my-trips'
    | '/offers'
    | '/request'
    | '/settings'
    | '/tracking'
    | '/trip-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DriverRoute: typeof DriverRoute
  LoadsRoute: typeof LoadsRoute
  MyBidsRoute: typeof MyBidsRoute
  MyRequestsRoute: typeof MyRequestsRoute
  MyTripsRoute: typeof MyTripsRoute
  OffersRoute: typeof OffersRoute
  RequestRoute: typeof RequestRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  TripDetailsRoute: typeof TripDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loads': {
      id: '/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof LoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bids': {
      id: '/my-bids'
      path: '/my-bids'
      fullPath: '/my-bids'
      preLoaderRoute: typeof MyBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-details': {
      id: '/trip-details'
      path: '/trip-details'
      fullPath: '/trip-details'
      preLoaderRoute: typeof TripDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DriverRoute: DriverRoute,
  LoadsRoute: LoadsRoute,
  MyBidsRoute: MyBidsRoute,
  MyRequestsRoute: MyRequestsRoute,
  MyTripsRoute: MyTripsRoute,
  OffersRoute: OffersRoute,
  RequestRoute: RequestRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  TripDetailsRoute: TripDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
